# Generated by Django 4.1.5 on 2023-02-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230131_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
