# Generated by Django 4.1.5 on 2023-02-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_login_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='name',
        ),
        migrations.RemoveField(
            model_name='login',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='login',
            name='user',
        ),
        migrations.AddField(
            model_name='login',
            name='fullname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='login',
            name='gender',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='login',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='dob',
            field=models.DateField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
