# Generated by Django 4.1.5 on 2023-02-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_login_name_remove_login_sex_remove_login_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(blank=True, default='user', max_length=20),
        ),
    ]
