# Generated by Django 4.1.5 on 2023-03-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='msg',
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
