# Generated by Django 4.1.7 on 2023-03-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_message_message_msg_alter_message_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='suname',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
