# Generated by Django 4.1.7 on 2023-04-12 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_message_suname'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date.today, max_length=10),
        ),
    ]
