# Generated by Django 4.1.7 on 2023-04-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='status',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='suname',
            field=models.CharField(blank=True, default='null', max_length=10),
        ),
    ]
