# Generated by Django 4.1.7 on 2023-04-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_login_status_alter_message_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
